var searchData=
[
  ['add_0',['Add',['../class_hospital___reservation___app_1_1_repositories_1_1_speciality_repository.html#aff2f6a95fe7268dcf2ffc114e990ab44',1,'Hospital_Reservation_App.Repositories.SpecialityRepository.Add()'],['../class_hospital___reservation___app_1_1_repositories_1_1_user_repository.html#acb405909216b63d19428e9d883b30b83',1,'Hospital_Reservation_App.Repositories.UserRepository.Add()']]],
  ['addcomment_1',['AddComment',['../class_hospital___reservation___app_1_1_repositories_1_1_grade_and_comment_repository.html#ab851c96fe015d883b4d6591bbb31e498',1,'Hospital_Reservation_App::Repositories::GradeAndCommentRepository']]],
  ['adddoctornote_2',['AddDoctorNote',['../class_hospital___reservation___app_1_1_repositories_1_1_doctor_note_repository.html#a97d6d2b1d9647edfb1223977b59c6b73',1,'Hospital_Reservation_App::Repositories::DoctorNoteRepository']]],
  ['addeventhandler_3',['AddEventHandler',['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)'],['../class_xaml_generated_namespace_1_1_generated_internal_type_helper.html#a73471f4a6d1ca4c4fceec9ad8610f0c8',1,'XamlGeneratedNamespace.GeneratedInternalTypeHelper.AddEventHandler(System.Reflection.EventInfo eventInfo, object target, System.Delegate handler)']]],
  ['addres_4',['AddRes',['../class_hospital___reservation___app_1_1_repositories_1_1_reservation_repository.html#a6e799cc7dc8525bde2323cdb6d746f5f',1,'Hospital_Reservation_App::Repositories::ReservationRepository']]],
  ['addreservationview_5',['AddReservationView',['../class_hospital___reservation___app_1_1_view_1_1_add_reservation_view.html',1,'Hospital_Reservation_App::View']]],
  ['addreservationviewmodel_6',['AddReservationViewModel',['../class_hospital___reservation___app_1_1_view_model_1_1_add_reservation_view_model.html',1,'Hospital_Reservation_App::ViewModel']]],
  ['adminview_7',['AdminView',['../class_hospital___reservation___app_1_1_view_1_1_admin_view.html',1,'Hospital_Reservation_App::View']]],
  ['adminviewmodel_8',['AdminViewModel',['../class_hospital___reservation___app_1_1_view_model_1_1_admin_view_model.html',1,'Hospital_Reservation_App::ViewModel']]],
  ['app_9',['App',['../class_hospital___reservation___app_1_1_app.html',1,'Hospital_Reservation_App']]],
  ['authentificateuser_10',['AuthentificateUser',['../class_hospital___reservation___app_1_1_repositories_1_1_user_repository.html#a392653547325df727487d3298022c0c9',1,'Hospital_Reservation_App::Repositories::UserRepository']]]
];
